HW4/HW4/Controllers/ColorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Drawing;
using System.Diagnostics;


namespace HW4.Controllers
{
    public class ColorController : Controller
    {
        /// <summary>
        /// It will create the Create view. This will be called when GET is requested.
        /// </summary>
        /// <returns>The Create view will be returned.</returns>
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// It will create the Create view. This will be called when Post is requested.
        /// </summary>
        /// <param name="colorA">This is the first hexadecimal color to mix.</param>
        /// <param name="colorB">This is the second hexadecimal color to mix.</param>
        /// <returns>The Create view will be returned.</returns>
        [HttpPost]
        public ActionResult Create(string colorA, string colorB)
        {
            string mixedColor = "#";
            //Check for invalid length of 4 or 5 for color string not including the #.
            //Note that html validation will already restrict length of colorA and colorB from 3 to 6.
            if (!(colorA.Length == 5 || colorA.Length == 6 || colorB.Length == 5 || colorB.Length == 6))
            {
                //Check if colorA and colorB are 3 character and adjust it to 6 if so, not conting the #.
                if (colorA.Length == 4)
                {
                    colorA = "#" + colorA[1] + colorA[1] + colorA[2] + colorA[2] + colorA[3] + colorA[3];
                }
                if (colorB.Length == 4)
                {
                    colorB = "#" + colorB[1] + colorB[1] + colorB[2] + colorB[2] + colorB[3] + colorB[3];
                }

                //Setup up mixedColor with mix of colorA and colorB.
                for (int i = 1; i <= 5; i += 2)
                {
                    //Convert part of colorA to decimal.
                    int colorDecimalA = Convert.ToInt32(colorA.Substring(i, 2), 16);
                    //Convert part of colorB to decimal.
                    int colorDecimalB = Convert.ToInt32(colorB.Substring(i, 2), 16);
                    //Check if addition of colorDecimalA and colorDecimalB is too high.
                    if (colorDecimalA + colorDecimalB >= 255)
                        mixedColor = mixedColor + "FF";
                    else
                    {
                        //Make sure that 0(s) is added properly when converting back to hexadecimal.
                        if (colorDecimalA + colorDecimalB == 0)
                            mixedColor = mixedColor + "00";
                        else if (colorDecimalA + colorDecimalB < 10)
                            mixedColor = mixedColor + "0" + (colorDecimalA + colorDecimalB).ToString("X");
                        else
                            mixedColor = mixedColor + (colorDecimalA + colorDecimalB).ToString("X");
                    }
                }
            }
           
            @ViewBag.first = colorA;
            @ViewBag.second = colorB;
            @ViewBag.result = mixedColor;
            return View();
        }

    }
}

HW4/HW4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HW4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// This will return the Converter view and pass converted miles to it.
        /// </summary>
        /// <returns> Return the Converter view.</returns>
        [HttpGet]
        public ActionResult Converter()
        {
            string miles = (Request.QueryString["miles"]);
            
            //If miles is not empty then convert to selected units.
            if(miles != null)
            {
                string units = (Request.QueryString["unit"]);
                double distance = 0;
                switch (units)
                {
                    case "millimeters":
                        distance = Convert.ToDouble(miles) * 1609344;
                        break;
                    case "centimeters":
                        distance = Convert.ToDouble(miles) * 160934.4;
                        break;
                    case "meters":
                        distance = Convert.ToDouble(miles) * 1609.344;
                        break;
                    case "kilometers":
                        distance = Convert.ToDouble(miles) * 1.609344;
                        break;
                }

                string message = miles + " miles is equal to " + distance + " " + units;
                ViewBag.message = message;
            }
            return View();
        }
    }
}

HW4/HW4/Views/Color/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create a New Color</h2>
<p>Please enter colors in HTML hexadecimal format: #AABBCC</p>

<!--create form here-->
@using (@Html.BeginForm("Create", "Color", FormMethod.Post))
{
    @Html.Label("first", "FirstColor")
    <br />
    <!--text box has form validation of starting with #, containing only A-F/a-f/0-9 characters and requiring string length of 3-6 after "#".-->
    @Html.TextBox("colorA", null, htmlAttributes: new { @class = "form-control", type = "text", pattern = "^[#]?[A-Fa-f0-9]{3,6}$", required = "required" })
    <br />
    @Html.Label("second", "SecondColor")
    <br />
    <!--same form validation as above textbox-->
    @Html.TextBox("colorB", null, htmlAttributes: new { @class = "form-control", type = "text", pattern = "^[#]?[A-Fa-f0-9]{3,6}$", required = "required" })
    <br />
    <br />
    @Html.TextBox("submited", "MixColors", htmlAttributes: new { @class = "btn btn-primary", type = "submit" })
    <br />

    <!--check if result color is set and desplay if it contains a valid value.-->
    <!-- Will give error if result only has #, caused from length of colorA or colorB being 4 or 5 not counting the #-->
    if (ViewBag.result != null && ViewBag.result != "#")
    {
        <br />
        <div class="container">
            <div class="col-md-2" style="width:100px; height:100px; border: 1px solid black; background:@ViewBag.first">
            </div>
            <h4 class="col-md-1 text-center"> + </h4>
            <div class="col-md-2" style="width:100px; height:100px; border: 1px solid black; background:@ViewBag.second">
            </div>
            <h4 class="col-md-1 text-center"> = </h4>
            <div class="col-md-2" style="width:100px; height:100px; border: 1px solid black; background:@ViewBag.result">
            </div>
        </div>
    }
    else if (ViewBag.result == "#")
    {
        <div class="alert alert-danger">Bad Input entered</div>
    }
}

HW4/HW4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Homework 4", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Converter", "Converter", "Home")</li>
                    <li>@Html.ActionLink("ColorChooser", "Create", "Color")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hector Acosta-Cervantes</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>